### ISSUE TITLE
Problem connecting to PostGIS

### ISSUE THREAD

**Issue by jesselangdon** [rburhum/arcgis-ogr#16]
When attempting to connect to a Postgres/PostGIS database from ArcMap 10.1 (Windows 7), I get the following error while trying to connect:

'''PG:dbname=basemap user="gis_admin" password=XXXXXX host=XX.X.X.XXX"

ERROR: permission denied for relation geometry_columns

followed by:

Error HRESULT E_FAIL has been returned from a call to a COM component

I have granted ownership of the geometry_columns table to gis_admin, so I'm not sure what the problem is.

**Comment by jesselangdon** [comment]
Argh.  Nevermind.  I realized I also needed to grant ownership privileges to gis_admin for the spatial_ref_sys table.  Please disregard!

**Comment by rburhum** [comment]
Great to hear it is working for you @jesselangdon . By the way, I would love to hear some feedback from you over e-mail if you get some free time. Thanks again
