### ISSUE TITLE
ArcGIS + PostGIS - Read/Write

### ISSUE THREAD

**Issue by eduardogspereira** [rburhum/arcgis-ogr#20]
Hi rburhum,

Thanks for sharing the code of application. Let me ask you a question, do you think that with GDAL I can be able of read/write from ArcGIS? I'm thinking of developing a code for it, if the answer is yes.

Thanks again.
eduardogspereira

**Comment by rburhum** [comment]
yes

On Tuesday, June 7, 2016, Eduardo Gustavo Soares Pereira <
notifications@github.com> wrote:

> Hi rburhum,
> 
> Thanks for sharing the code of application. Let me ask you a question, do
> you think that with GDAL I can be able of read/write from ArcGIS? I'm
> thinking of developing a code for it, if the answer is yes.
> 
> Thanks again.
> eduardogspereira
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rburhum/arcgis-ogr/issues/20, or mute the thread
> https://github.com/notifications/unsubscribe/AAIepl7bMLDJ5oiXSbf3-8KADlsNHnUsks5qJWOvgaJpZM4Iv3bz
> .

## 

_Ragi Burhum_

+1 (415) 935-1447
ragi@amigocloud.com
linkedin.com/in/rburhum

**Comment by eduardogspereira** [comment]
Thanks! :)
