### ISSUE TITLE
SpatiaLite Spatial Index residues

### ISSUE THREAD

**Issue by Bescu** [rburhum/arcgis-ogr#3]
Hello,

I found another little bug when I try to open a SpatiaLite Database with Spatial Indexes residues of table that have been deleted : I have this error message : "Unable to query table EDI_PARC_pt_locaux_VAC for column definitions : no such table: EDI_PARC_pt_locaux_VAC."

The solution is to delete theses Spatial Indexes from the SpatiaLite Database.

**Comment by Bescu** [comment]
Finaly, I thing it's not the Spatial Indexes but the geometry_columns residues of tables that have benne deleted!

**Comment by rburhum** [comment]
To understand this better. You had an entry in a geometry_columns table, but the table did not exist anymore?

**Comment by Bescu** [comment]
Yes, it's exactly that! It's a little my fault : the db wasn't "cleaned" but I prefered to warn you this!

**Comment by rburhum** [comment]
Good to know. That's a GDAL spatialite driver problem. AFAIK, spatialite itself will move to make those table views (just like PostGIS 2.0 just did). That will automatically make this go away. I will close the issue here and take it there.
