### ISSUE TITLE
Geometry fails to be converted in KML files

### ISSUE THREAD

**Issue by petr-k** [rburhum/arcgis-ogr#5]
KML files fail to process geometry properly. I tested with this file https://developers.google.com/kml/documentation/KML_Samples.kml, document "Placemarks".

The problem lies in OGRCursor.QueryGeometry. When IWkb.ImportFromWkb is called, it throws an exception "expected wkbPoint type in wkb stream". The original OGR geometry seems to be okay, though (checked by converting to WKT).

It may be related to the fact that the geometry type is PointZ (the KML file contains elevation information).

**Comment by rburhum** [comment]
Can you open witg the libkml driver and then with the built-in kml driver and see if there is a difference? I am in Machu Picchu now and dont have anything better than a smartphone :)

**Comment by petr-k** [comment]
I might do that, but just found that after flattening the geometry with Geometry.FlattenTo2D(), IWkb.ImportFromWkb imports the geometry just fine.

Looks like Esri WKB implementation does not support Z values, using a different KML driver probably won't help since it should produce the same WKB.

**Comment by rburhum** [comment]
You are completely correct. The Import to WKB is failing. I have added https://github.com/RBURHUM/arcgis-ogr/issues/11 to add Z support. In the meantime, I will fix this bug by calling FlattenTo2D() as you suggested.

**Comment by rburhum** [comment]
Interestingly enough, too, I noticed very different number of fields between the libkml trunk driver and the built-in KML driver. I think I will bundle the libkml driver.

**Comment by rburhum** [comment]
#11 will track the Z support and this commit https://github.com/RBURHUM/arcgis-ogr/commit/f10d97b20b339c8a70354ce147ad9934c16eecf8 will take care of at least being able to read the geometries in 2D. Thank you ptr-k!
